os:
  - linux

sudo: required 

dist: precise

language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  #- "2.6"
  #- "2.7"
  #- "3.3"
  #- "3.4"
  - "3.6.1"

# command to install dependencies
install:
  - sudo apt-get update
# - pip install .
# - pip install -r requirements.txt

  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - echo TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  #- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION dep1 dep2 ...
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  #- python setup.py install
  - while read requirement; do conda install --yes $requirement; done < requirements.txt

# command to run tests
script:
  #- pytest
  - python tests/test_*.py
